### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by Spacerulerwill** [Ariel4545/text_editor#4]
It would helpful for people who wish to run the project from source for there to be a requirements.txt file. I would submit a pull request and create one myself, but I do not know if there are any specific version requirements for any of the libraries used

**Comment by Ariel4545** [comment]
I added one, the libraries' version doesn't matter for the program, except the googletrans library but it doesn't required (:, Also I have a problem with my venv so When I will find the specific version I will add them anyway. thank you
